// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpuusdbjsvitugsnzfma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdXVzZGJqc3ZpdHVnc256Zm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjUxNzMsImV4cCI6MjA1OTk0MTE3M30.oZt0DhqKVL7rSjAABaiLdSKYKIkF-5s_vljco_S5KzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);